### ISSUE TITLE
实验手册实验二中的优先级调度算法

### ISSUE THREAD

**Issue by reticenceji** [ZJU-SEC/os23fall-stu#3]
实验手册实验二中的优先级调度算法，让同学参考Linux 的实现。但是Linux的实现和教科书中的优先级调度算法并不是一致的，建议换一个名字，以免给同学带来误解。

**Comment by NeilAlfred** [comment]
如果你说的“教科书中的优先级调度算法”指的是“优先级越高，越优先分配”，那你可以在 `make run` 情况下看一眼第二轮调度的时候，各个线程的调度情况。这个实验不涉及线程抢占，在“优先级调度算法”下，从第二轮开始所有线程 `counter = priority` 。不知道这样说同学你能否理解 👀

**Comment by reticenceji** [comment]
我可以理解，linux 0.11的算法可以说是 "longest job first" ，然后priority越高时间片越长。只是如果直接按照教科书上的理解，priority高的在第一轮也应该直接被优先执行了，这样容易给同学们造成困扰

**Comment by NeilAlfred** [comment]
那我加个说明进实验指导里好了。我第一次加这个测试确实考虑不周，明年应该调整成 `priority` 调度下测试样例 `priority=counter` 会好一点。

**Comment by NeilAlfred** [comment]
第一次当助教，今年加调度的测试有点匆忙，明年我考虑升级成对于多轮调度的测试，这样就不会有类似的疑惑了。
